# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "7ef833bedb14fe7fc55e6788cc99da0d277c1742e9efd3f1bdd1c04967a5bd9b"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
  infinite_scroll: true
  query_in_title: true
redis:
  url: redis://redis:6379/0
general:
  debug: false
  instance_name: "CatCatGo"
  contact_url: "mailto:minna.melq.andrade@gmail.com"
  enable_metrics: true
search:
  safe_search: 1
  autocomplete: "google"